services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: prospect-sync-backend-prod
    restart: unless-stopped
    ports:
      - "5102:5102"
    env_file:
      - .env.prod
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5102/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - prospect-sync-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
      args:
        - VITE_API_URL=http://192.168.0.21:5102
    container_name: prospect-sync-frontend-prod
    restart: unless-stopped
    ports:
      - "3020:3020"
    env_file:
      - .env.prod
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3020"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - prospect-sync-network

networks:
  prospect-sync-network:
    driver: bridge 