version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: prospect-sync-backend-prod
    restart: unless-stopped
    ports:
      - "5102:5102"
    env_file:
      - .env.prod
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ASPNETCORE_URLS=${ASPNETCORE_URLS}
      - ConnectionStrings__Tfclive=${CONNECTIONSTRINGS__TFCLIVE}
      - ConnectionStrings__Sr=${CONNECTIONSTRINGS__SR}
      - Jwt__Secret=${JWT__SECRET}
      - Jwt__Issuer=${JWT__ISSUER}
      - Jwt__Audience=${JWT__AUDIENCE}
      - Jwt__ExpirationInMinutes=${JWT__EXPIRATIONINMINUTES}
      - ActiveDirectory__Server=${ACTIVEDIRECTORY__SERVER}
      - ActiveDirectory__Domain=${ACTIVEDIRECTORY__DOMAIN}
      - ActiveDirectory__Timeout=${ACTIVEDIRECTORY__TIMEOUT}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5102/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - prospect-sync-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: prospect-sync-frontend-prod
    restart: unless-stopped
    ports:
      - "3020:80"
    env_file:
      - .env.prod
    environment:
      - VITE_API_URL=${VITE_API_URL}
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - prospect-sync-network

networks:
  prospect-sync-network:
    driver: bridge 